use EFCore;

INSERT INTO Estado VALUES('São Paulo', 'SP')
GO

INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Adamantina', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Adolfo', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Agisse', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Agua Vermelha', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Aguai', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Aguas da Prata', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Aguas de Lindoia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Aguas de Santa Barbara', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Aguas de Sao Pedro', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Agudos', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Agulha', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Ajapi', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Alambari', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Alberto Moreira', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Aldeia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Aldeia de Carapicuiba', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Alfredo Guedes', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Alfredo Marcondes', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Altair', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Altinopolis', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Alto Alegre', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Alto Pora', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Aluminio', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Alvares Florence', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Alvares Machado', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Alvaro de Carvalho', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Alvinlandia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Amadeu Amaral', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Amandaba', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Ameliopolis', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Americana', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Americo Brasiliense', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Americo de Campos', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Amparo', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Ana Dias', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Analandia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Anapolis', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Andes', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Andradina', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Angatuba', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Anhembi', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Anhumas', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Aparecida', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Aparecida D''Oeste', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Aparecida de Monte Alto', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Aparecida de Sao Manuel', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Aparecida do Bonito', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Apiai', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Arabela', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Aracacu', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Aracaiba', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Aracariguama', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Aracatuba', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Aracoiaba da Serra', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Aramina', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Arandu', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Arapei', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Araraquara', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Araras', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Araxas', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Arcadas', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Arco-Iris', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Arealva', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Areias', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Areiopolis', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Ariranha', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Ariri', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Artemis', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Artur Nogueira', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Aruja', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Aspasia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Assis', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Assistencia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Atibaia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Atlantida', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Auriflama', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Avai', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Avanhandava', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Avare', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Avencas', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Bacaetava', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Bacuriti', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Bady Bassitt', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Baguacu', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Bairro Alto', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Balbinos', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Balsamo', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Bananal', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Barao Ataliba Nogueira', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Barao de Antonina', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Barao de Geraldo', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Barbosa', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Bariri', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Barra Bonita', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Barra do Chapeu', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Barra do Turvo', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Barra Dourada', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Barrania', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Barretos', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Barrinha', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Barueri', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Bastos', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Batatais', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Batatuba', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Batista Botelho', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Bauru', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Bebedouro', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Bela Floresta', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Bela Vista Sao-Carlense', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Bento de Abreu', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Bernardino de Campos', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Bertioga', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Bilac', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Birigui', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Biritiba-Mirim', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Biritiba-Ussu', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Boa Esperanca do Sul', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Boa Vista dos Andradas', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Boa Vista Paulista', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Bocaina', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Bofete', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Boituva', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Bom Fim do Bom Jesus', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Bom Jesus dos Perdoes', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Bom Retiro da Esperanca', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Bom Sucesso de Itarare', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Bonfim Paulista', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Bora', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Boraceia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Borborema', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Borebi', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Botafogo', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Botelho', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Botucatu', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Botujuru', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Braco', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Braganca Paulista', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Bras Cubas', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Brasitania', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Brauna', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Brejo Alegre', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Brigadeiro Tobias', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Brodowski', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Brotas', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Bueno de Andrada', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Buri', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Buritama', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Buritizal', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Cabralia Paulista', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Cabreuva', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Cacapava', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Cachoeira de Emas', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Cachoeira Paulista', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Caconde', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Cafelandia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Cafesopolis', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Caiabu', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Caieiras', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Caiua', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Cajamar', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Cajati', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Cajobi', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Cajuru', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Cajuru do Sul', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Cambaquara', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Cambaratiba', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Campestrinho', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Campina do Monte Alegre', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Campinal', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Campinas', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Campo Limpo Paulista', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Campos de Cunha', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Campos do Jordao', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Campos Novos Paulista', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Cananeia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Canas', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Candia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Candido Mota', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Candido Rodrigues', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Canguera', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Canitar', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Capao Bonito', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Capela do Alto', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Capivari', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Capivari da Mata', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Caporanga', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Capuava', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Caraguatatuba', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Carapicuiba', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Cardeal', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Cardoso', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Casa Branca', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Cassia dos Coqueiros', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Castilho', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Catanduva', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Catigua', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Catucaba', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Caucaia do Alto', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Cedral', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Cerqueira Cesar', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Cerquilho', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Cesario Lange', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Cezar de Souza', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Charqueada', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Chavantes', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Cidade Kemel', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Clarinia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Clementina', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Colina', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Colombia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Conceicao de Monte Alegre', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Conchal', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Conchas', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Cordeiropolis', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Coroados', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Coronel Goulart', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Coronel Macedo', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Corredeira', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Corrego Rico', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Corumbatai', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Cosmopolis', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Cosmorama', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Costa Machado', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Cotia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Cravinhos', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Cristais Paulista', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Cruz das Posses', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Cruzalia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Cruzeiro', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Cubatao', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Cuiaba Paulista', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Cunha', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Curupa', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Dalas', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Descalvado', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Diadema', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Dirce Reis', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Dirceu', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Divinolandia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Dobrada', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Dois Corregos', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Dolcinopolis', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Domelia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Dourado', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Dracena', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Duartina', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Dumont', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Duplo Ceu', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Echapora', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Eden', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Eldorado', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Eleuterio', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Elias Fausto', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Elisiario', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Embauba', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Embu', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Embu-Guacu', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Emilianopolis', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Eneida', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Engenheiro Balduino', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Engenheiro Coelho', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Engenheiro Schmidt', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Ermelino Matarazzo', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Esmeralda', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Esperanca D''Oeste', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Espigao', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Espirito Santo do Pinhal', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Espirito Santo do Turvo', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Estiva Gerbi', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Estrela D''Oeste', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Estrela do Norte', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Euclides da Cunha Paulista', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Eugenio de Melo', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Fartura', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Fatima', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Fatima Paulista', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Fernando Prestes', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Fernandopolis', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Fernao', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Ferraz de Vasconcelos', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Flora Rica', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Floreal', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Floresta do Sul', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Florida Paulista', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Florinea', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Franca', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Francisco Morato', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Franco da Rocha', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Frutal do Campo', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Gabriel Monteiro', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Galia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Garca', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Gardenia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Gastao Vidigal', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Gaviao Peixoto', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'General Salgado', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Getulina', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Glicerio', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Gramadinho', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Guachos', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Guaianas', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Guaianazes', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Guaicara', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Guaimbe', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Guaira', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Guamium', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Guapiacu', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Guapiara', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Guapiranga', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Guara', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Guaracai', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Guaraci', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Guaraciaba D''Oeste', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Guarani D''Oeste', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Guaranta', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Guarapiranga', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Guarapua', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Guararapes', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Guararema', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Guaratingueta', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Guarei', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Guariba', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Guariroba', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Guarizinho', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Guaruja', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Guarulhos', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Guatapara', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Guzolandia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Herculandia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Holambra', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Hortolandia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Iacanga', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Iacri', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Iaras', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Ibate', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Ibiporanga', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Ibira', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Ibirarema', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Ibitinga', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Ibitiruna', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Ibitiuva', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Ibitu', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Ibiuna', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Icem', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Ida Iolanda', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Iepe', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Igacaba', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Igaracu do Tiete', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Igarai', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Igarapava', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Igarata', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Iguape', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Ilha Comprida', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Ilha Solteira', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Ilhabela', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Indaia do Aguapei', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Indaiatuba', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Indiana', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Indiapora', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Ingas', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Inubia Paulista', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Ipaussu', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Ipero', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Ipeuna', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Ipigua', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Iporanga', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Ipua', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Iracemapolis', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Irape', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Irapua', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Irapuru', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Itabera', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Itai', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Itaim Paulista', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Itaiuba', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Itajobi', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Itaju', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Itanhaem', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Itaoca', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Itapecerica da Serra', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Itapetininga', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Itapeuna', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Itapeva', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Itapevi', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Itapira', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Itapirapua Paulista', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Itapolis', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Itaporanga', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Itapui', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Itapura', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Itaquaquecetuba', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Itaquera', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Itaqueri da Serra', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Itarare', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Itariri', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Itatiba', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Itatinga', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Itirapina', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Itirapua', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Itobi', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Itororo do Paranapanema', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Itu', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Itupeva', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Ituverava', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Iubatinga', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Jaborandi', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Jaboticabal', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Jacare', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Jacarei', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Jaci', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Jacipora', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Jacuba', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Jacupiranga', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Jafa', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Jaguariuna', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Jales', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Jamaica', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Jambeiro', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Jandira', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Jaragua', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Jardim Belval', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Jardim Presidente Dutra', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Jardim Santa Luzia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Jardim Silveira', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Jardinopolis', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Jarinu', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Jatoba', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Jau', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Jeriquara', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Joanopolis', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Joao Ramalho', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Joaquim Egidio', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Jordanesia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Jose Bonifacio', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Juliania', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Julio Mesquita', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Jumirim', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Jundiai', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Jundiapeba', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Junqueira', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Junqueiropolis', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Juquia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Juquiratiba', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Juquitiba', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Juritis', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Juruce', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Jurupeba', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Jurupema', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Lacio', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Lagoa Azul', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Lagoa Branca', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Lagoinha', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Laranjal Paulista', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Laras', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Lauro Penteado', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Lavinia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Lavrinhas', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Leme', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Lencois Paulista', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Limeira', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Lindoia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Lins', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Lobo', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Lorena', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Lourdes', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Louveira', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Lucelia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Lucianopolis', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Luis Antonio', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Luiziania', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Lupercio', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Lusitania', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Lutecia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Macatuba', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Macaubal', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Macedonia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Macucos', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Magda', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Mailasqui', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Mairinque', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Mairipora', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Major Prado', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Manduri', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Mangaratu', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Maraba Paulista', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Maracai', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Marapoama', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Marcondesia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Maresias', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Mariapolis', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Marilia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Marinopolis', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Maristela', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Martim Francisco', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Martinho Prado Junior', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Martinopolis', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Matao', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Maua', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Mendonca', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Meridiano', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Mesopolis', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Miguelopolis', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Mineiros do Tiete', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Mira Estrela', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Miracatu', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Miraluz', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Mirandopolis', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Mirante do Paranapanema', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Mirassol', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Mirassolandia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Mococa', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Mogi das Cruzes', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Mogi-Guacu', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Mogi-Mirim', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Mombuca', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Moncoes', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Mongagua', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Montalvao', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Monte Alegre do Sul', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Monte Alto', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Monte Aprazivel', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Monte Azul Paulista', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Monte Castelo', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Monte Mor', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Monte Verde Paulista', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Monteiro Lobato', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Moreira Cesar', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Morro Agudo', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Morro do Alto', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Morungaba', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Mostardas', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Motuca', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Mourao', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Murutinga do Sul', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Nantes', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Narandiba', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Natividade da Serra', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Nazare Paulista', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Neves Paulista', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Nhandeara', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Nipoa', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Nogueira', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Nossa Senhora do Remedio', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Nova Alexandria', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Nova Alianca', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Nova America', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Nova Aparecida', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Nova Campina', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Nova Canaa Paulista', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Nova Castilho', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Nova Europa', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Nova Granada', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Nova Guataporanga', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Nova Independencia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Nova Itapirema', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Nova Luzitania', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Nova Odessa', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Nova Patria', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Nova Veneza', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Novais', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Novo Cravinhos', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Novo Horizonte', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Nuporanga', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Oasis', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Ocaucu', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Oleo', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Olimpia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Oliveira Barros', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Onda Branca', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Onda Verde', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Oriente', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Orindiuva', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Orlandia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Osasco', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Oscar Bressane', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Osvaldo Cruz', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Ourinhos', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Ouro Fino Paulista', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Ouro Verde', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Pacaembu', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Padre Nobrega', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Palestina', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Palmares Paulista', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Palmeira D''Oeste', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Palmeiras de Sao Paulo', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Palmital', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Panorama', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Paraguacu Paulista', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Paraibuna', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Paraiso', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Paraisolandia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Paranabi', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Paranapanema', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Paranapiacaba', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Paranapua', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Parapua', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Pardinho', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Parelheiros', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Pariquera-Acu', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Parisi', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Parnaso', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Parque Meia Lua', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Paruru', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Patrocinio Paulista', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Pauliceia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Paulinia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Paulistania', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Paulo de Faria', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Paulopolis', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Pederneiras', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Pedra Bela', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Pedra Branca de Itarare', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Pedranopolis', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Pedregulho', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Pedreira', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Pedrinhas Paulista', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Pedro Barros', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Pedro de Toledo', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Penapolis', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Pereira Barreto', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Pereiras', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Peruibe', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Perus', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Piacatu', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Picinguaba', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Piedade', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Pilar do Sul', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Pindamonhangaba', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Pindorama', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Pinhalzinho', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Pinheiros', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Pioneiros', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Piquerobi', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Piquete', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Piracaia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Piracicaba', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Piraju', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Pirajui', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Piramboia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Pirangi', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Pirapitingui', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Pirapora do Bom Jesus', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Pirapozinho', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Pirassununga', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Piratininga', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Pitangueiras', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Planalto', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Planalto do Sul', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Platina', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Poa', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Poloni', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Polvilho', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Pompeia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Pongai', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Pontal', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Pontalinda', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Pontes Gestal', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Populina', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Porangaba', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Porto Feliz', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Porto Ferreira', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Porto Novo', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Porto Primavera', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Potim', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Potirendaba', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Potunduva', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Pracinha', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Pradinia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Pradopolis', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Praia Grande', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Pratania', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Presidente Alves', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Presidente Bernardes', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Presidente Epitacio', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Presidente Prudente', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Presidente Venceslau', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Promissao', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Prudencio e Moraes', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Quadra', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Quata', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Queiroz', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Queluz', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Quintana', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Quiririm', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Rafard', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Rancharia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Rechan', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Redencao da Serra', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Regente Feijo', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Reginopolis', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Registro', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Restinga', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Riacho Grande', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Ribeira', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Ribeirao Bonito', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Ribeirao Branco', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Ribeirao Corrente', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Ribeirao do Sul', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Ribeirao dos Indios', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Ribeirao Grande', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Ribeirao Pires', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Ribeirao Preto', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Ribeiro do Vale', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Ribeiro dos Santos', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Rifaina', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Rincao', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Rinopolis', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Rio Claro', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Rio das Pedras', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Rio Grande da Serra', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Riolandia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Riversul', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Roberto', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Rosalia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Rosana', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Roseira', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Rubiacea', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Rubiao Junior', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Rubineia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Ruilandia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sabauna', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sabino', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sagres', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sales', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sales Oliveira', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Salesopolis', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Salmourao', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Saltinho', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Salto', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Salto de Pirapora', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Salto do Avanhandava', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Salto Grande', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sandovalina', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Santa Adelia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Santa Albertina', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Santa America', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Santa Barbara D''Oeste', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Santa Branca', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Santa Clara D''Oeste', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Santa Cruz da Conceicao', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Santa Cruz da Esperanca', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Santa Cruz da Estrela', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Santa Cruz das Palmeiras', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Santa Cruz do Rio Pardo', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Santa Cruz dos Lopes', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Santa Ernestina', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Santa Eudoxia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Santa Fe do Sul', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Santa Gertrudes', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Santa Isabel', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Santa Isabel do Marinheiro', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Santa Lucia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Santa Margarida Paulista', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Santa Maria da Serra', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Santa Maria do Gurupa', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Santa Mercedes', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Santa Rita D''Oeste', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Santa Rita do Passa Quatro', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Santa Rita do Ribeira', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Santa Rosa de Viterbo', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Santa Salete', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Santa Teresinha de Piracicaba', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Santana da Ponte Pensa', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Santana de Parnaiba', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Santelmo', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Santo Anastacio', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Santo Andre', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Santo Antonio da Alegria', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Santo Antonio da Estiva', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Santo Antonio de Posse', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Santo Antonio do Aracangua', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Santo Antonio do Jardim', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Santo Antonio do Paranapanema', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Santo Antonio do Pinhal', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Santo Antonio Paulista', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Santo Expedito', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Santopolis do Aguapei', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Santos', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sao Benedito da Cachoeirinha', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sao Benedito das Areias', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sao Bento do Sapucai', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sao Bernardo do Campo', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sao Berto', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sao Caetano do Sul', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sao Carlos', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sao Francisco', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sao Francisco da Praia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sao Francisco Xavier', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sao Joao da Boa Vista', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sao Joao das Duas Pontes', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sao Joao de Iracema', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sao Joao de Itaguacu', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sao Joao do Marinheiro', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sao Joao do Pau D''Alho', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sao Joao Novo', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sao Joaquim da Barra', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sao Jose da Bela Vista', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sao Jose das Laranjeiras', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sao Jose do Barreiro', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sao Jose do Rio Pardo', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sao Jose do Rio Preto', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sao Jose dos Campos', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sao Lourenco da Serra', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sao Lourenco do Turvo', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sao Luis do Paraitinga', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sao Luiz de Guaricanga', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sao Manuel', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sao Martinho D''Oeste', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sao Mateus', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sao Miguel Arcanjo', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sao Miguel Paulista', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'São Paulo', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sao Pedro', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sao Pedro do Turvo', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sao Roque', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sao Roque da Fartura', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sao Sebastiao', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sao Sebastiao da Grama', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sao Sebastiao da Serra', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sao Silvestre de Jacarei', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sao Simao', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sao Vicente', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sapezal', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sapopemba', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sarapui', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sarutaia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sebastianopolis do Sul', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Serra Azul', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Serra Negra', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Serrana', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sertaozinho', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sete Barras', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Severinia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Silvania', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Silveiras', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Simoes', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Simonsen', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Socorro', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sodrelia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Solemar', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sorocaba', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sousas', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sud Menucci', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sumare', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Sussui', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Suzano', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Suzanopolis', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Tabajara', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Tabapua', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Tabatinga', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Taboao da Serra', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Taciba', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Taguai', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Taiacu', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Taiacupeba', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Taiuva', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Talhado', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Tambau', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Tanabi', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Tapinas', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Tapirai', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Tapiratiba', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Taquaral', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Taquaritinga', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Taquarituba', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Taquarivai', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Tarabai', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Taruma', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Tatui', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Taubate', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Tecainda', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Tejupa', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Teodoro Sampaio', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Terra Nova D''Oeste', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Terra Roxa', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Tibirica', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Tibirica do Paranapanema', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Tiete', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Timburi', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Toledo', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Torre de Pedra', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Torrinha', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Trabiju', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Tremembe', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Tres Aliancas', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Tres Fronteiras', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Tres Pontes', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Tres Vendas', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Tuiuti', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES('Tujuguaba', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Tupa', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Tupi', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Tupi Paulista', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Turiba do Sul', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Turiuba', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Turmalina', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Turvinia', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Ubarana', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Ubatuba', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Ubirajara', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Uchoa', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Uniao Paulista', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Universo', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Urania', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Uru', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Urupes', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Ururai', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Vale Formoso', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Valentim Gentil', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Valinhos', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Valparaiso', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Vangloria', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Vargem', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Vargem Grande do Sul', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Vargem Grande Paulista', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Varpa', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Varzea Paulista', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Venda Branca', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Vera Cruz', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Vicente de Carvalho', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Vicentinopolis', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Vila Dirce', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Vila Nery', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Vila Xavier', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Vinhedo', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Viradouro', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Vista Alegre do Alto', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Vitoria Brasil', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Vitoriana', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Votorantim', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Votuporanga', 1);
INSERT INTO Cidade (Nome,EstadoID)  VALUES( 'Zacarias', 1);
GO
